### PR TITLE
Database sync

### PR DESCRIPTION
**Pull request by van3396**
used axios to sync database from API

### CODE REVIEW

**Comment by john-yo-ahn** [comment]
Approved!

**Comment by van3396** [comment]
approved

**Review by john-yo-ahn — APPROVED** [review]
Approved!

**Comment by thespiritfox** [comment]
Approved

**Review by john-yo-ahn — APPROVED** [review]
Approved!

**Review by thespiritfox — APPROVED** [review]
Approve

**Review by AnthonyMCorreia — APPROVED** [review]
good to go.

**Pull request merged**
